site_name: Terminal REST API

theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  features:
    - navigation.expand
    - navigation.instant
    #    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    - content.tooltips
    - content.tabs.link

markdown_extensions:
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

nav:
  - Getting started: index.md
