site_name: Terminal REST API

theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  features:
#    - navigation.expand
    - navigation.instant
    #    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.top
#    - navigation.tracking
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - search.suggest
    - search.highlight

markdown_extensions:
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

nav:
  - Getting started: index.md
  - Requests: requests.md
  - Responses: responses.md
  - Authorization: auth/index.md
  - Cash In:
      - Cash In - Introduction : cash_in/index.md
      - Flow diagram: cash_in/flow.md
      - Cheque generation: cash_in/cheque_generation.md
  - Users:
      - Retrieve user: users/retrieve.md
  - Daily:
      - Daily requests - Introduction : daily/index.md
      - Reports: daily/reports.md
      - Fees: daily/fees.md
      - Payments: daily/payments.md
      - Constants: daily/constants.md
  - Transactions:
      - Statuses: transactions/statuses.md
      - Status by external id: transactions/status_by_external_id.md
      - Status by internal id: transactions/status_by_internal_id.md
      - Cash In deposit: transactions/cash_in.md
      - Pay For Service: transactions/send_payment.md
  - Payments:
      - Payments - Introduction: payments/index.md
      - Payment Schema: payments/get_payment_schema.md
      - Flow diagram: payments/flow.md
      - Create payment: payments/create.md
      - Cheque generation: payments/cheque_generation.md
      - Daily requests: daily/payments.md
  - Fees:
      - Fees - Introduction : fees/index.md
      - Fees: fees/fees.md
      - Policies: fees/policies.md
      - Daily requests: daily/fees.md
  - Reports:
      - Reports - Introduction : reports/index.md
      - Daily requests: daily/reports.md
  - Idempotency: idempotency.md
